---
- name: installing and launching metricbeat
  hosts: webservers
  become: yes
  tasks:

  - name: download metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.7.1-amd64.deb

  - name: install metricbeat deb
    command: dpkg -i metricbeat-7.7.1-amd64.deb
    become: yes
    become_user: root

  - name: drop in metricbeat.yml
    copy:
      src: /etc/ansible/files/metricbeat-configuration.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure system module
    command: metricbeat modules enable docker
    become: yes
    become_user: root

  - name: setup metricbeat
    command: metricbeat setup
    become: yes
    become_user: root

  - name: start metricbeat service
    command: service metricbeat start
    become: yes
    become_user: root
